### ISSUE TITLE
Bungeecord compatibility

### ISSUE THREAD

**Issue by devryb** [BluSunrize/TravellersGear#26]
Using the mod with Bungeecord the players are immediately kicked when opening their inventory.
Here is what the console shows during the error

http://pastebin.com/ka6J3SGT

**Comment by BluSunrize** [comment]
Yeah a similar bug has been reported with morph. Fixed in version 1.16

**Comment by devryb** [comment]
Can you link me the 1.16 code? Curious what was done to fix it.

**Comment by BluSunrize** [comment]
I'll push to git later.

**Comment by devryb** [comment]
Thanks!

**Comment by BluSunrize** [comment]
Actually scratch that, you wont see the fix
The version on this repo is 1.15, my next push will be 1.16.1, you'll never get to see 1.16
Basically I just added a null check (because for some reason, some mods like Morph and apparently Bungeecord somehow break entity IDs)
This might still impact the game (NBT not getting synced properly), but I blame that on them. A player should never be null.

**Comment by devryb** [comment]
Confirmed 1.16.1 fixed bungeecord issues
