### ISSUE TITLE
Lacks a LICENSE file.

### ISSUE THREAD

**Issue by Rukachan** [BluSunrize/TravellersGear#39]

**Comment by BluSunrize** [comment]
...so?

**Comment by Rukachan** [comment]
Okay, let me explain:
Your curse page claims this project is "Public Domain".
Yet, considering that this project lacks a file, a comment on the top of the source or anything at all that contains the license of this project, it is not public domain. The rights to distribute or distribute a modified version (binary or source) are not given by default.
If you do not wish this project to be in "Public domain", then please change the description of the curse page. If you do wish this project to be in "Public domain", then please put the license of it somewhere.
It would also be advisable to select a "solid" public domain license, such as CC0 or something, due to some countries not having have public domain.

Also consider checking https://help.github.com/articles/open-source-licensing/

**Comment by BluSunrize** [comment]
Which still brings up the question why this is relevant. Are you trying to redistribute my code?

**Comment by HiggsBonbon** [comment]
Someone will if you don't explicitly explain what you do or don't want done with the code, it's that simple.

**Comment by BluSunrize** [comment]
Not really. If no license is given on Git, it is to be considered "All rights reserved". Unpermitted redistribution of my work is a legal case.
However, problem solved, CurseForge license updated.

**Comment by Rukachan** [comment]
No, I am trying to fork it, replace all the textures with big, fucking, giant, precummed horsedicks and then distribute it, together with my jars. May I have my answer already? Or if don't want it redistributed/modified, why did you select its license to be "public domain" at curse? It's like you try to trick people.
Finally you could for once try to avoid this annoying shit-eating ironic behaviour.

**Comment by projectilemotion** [comment]
>Which still brings up the question why this is relevant. Are you trying to redistribute my code?

It is relevant because you are hosting your code on a website which is, by and large, for open source repositories of code. Further, as Rukachan said, there seems to be a discrepancy with the Curse page.

Whether or not Rukachan personally wants to redistribute your code is irrelevant. For example, I have no intention on redistributing your code, but I am kindly asking that you use an open source license for your project, as this is likely to attract contributors and contribute to the Minecraft ecosystem in a positive way.

There exist people who do want to redistribute code, and I do not think it is right that you do not allow them to do this. You are shutting out potential contributors and users, which is a net loss to you and the community.

Please reconsider your decision; there are many Minecraft mods that are open source, and you would lose nothing by open sourcing your work.

Thanks!

**Comment by projectilemotion** [comment]
I'd also like to add that you have not given any rights to clone the code or to compile the code or to run the code. The only thing that people who see this repository are allowed to do is to read the code.

If we go by your standard of "all rights reserved", nobody has the right to run your code, and thus nobody will run your mod - this is because you did not select an appropriate license.

Will you take people who run your mod to court?

**Comment by BluSunrize** [comment]
No, sorry, irony and sarcasm are my thing, can't help that.

You're free to play my mod, look at my code and take inspiration from it like you'd do with any other mod on github.
You are no allowed to fork or redistrtibute my code without my explicit permission.

Does that clear up all questions?

**Comment by projectilemotion** [comment]
I'm just curious, why is redistribution not allowed?

**Comment by BluSunrize** [comment]
Because it's my work and I actually kinda earn money with it? Curse gives you points based on download numbers. That and Patreon are my only income sources, so I'm kinda happy I have those.

**Comment by projectilemotion** [comment]
Making your project open source does not mean you will not get any money from it. People can already read the code, in fact.

Nobody is going to come along and pass off your work as their own - in fact, most if not all open source licenses (aside from public domain) stop people from doing this. You will always be credited, and if you are not credited then it is a license violation.

Either way you need to worry about license violations - in the current situation where someone will redistribute your code (any code after your project was public domain) and the open source situation where people will not credit you.

It's worth remembering that the first situation *by far* outnumbers the second situation. Within the open source community there is generally a sense of respect and adhering to the terms of a license, even in the most cold hearted of people.

By not having your project open source, you are setting yourself up for license violations which you can do very little about in a court of law because of your project's non-legalese license.

If it's money you're worried about losing, I can assure you, that you will lose none in potential profits. If someone were to fork your project and put it on Curse, the license terms would stipulate that they must link to you - and people would quickly realise that the person who forked it put in a smaller amount of effort than you did toward the project.

There are even licenses such as the GNU GPL that require other projects to also have the *same* license. Any benefit they gain (be it in money or otherwise), you can catch up on by re-merging the code back into your repo. No other fork of your work would have any edge over yours - yet with the current situation, a violator, looking to make his/her biggest violation, would go for your current code (on GitHub) and make it proprietary, meaning that you have no legal entitlement to any benefit, code or otherwise.

And of course you can always change the license back if you so desire, as you just did not long ago.

Open sourcing is a net benefit.

**Comment by projectilemotion** [comment]
It's also worth mentioning that your code is an API, and nobody will dare touch it with a license like you currently have. It seems you are caught between having your custom non-free license and having nobody use your code. And if nobody uses the API, what money would you get in this case?

**Comment by asiekierka** [comment]
>The API is designed to allow other modders to acces the extended inventory and add their own custom items. 

No, no it's not. I cannot put the API in my source code project without breaking your license. I cannot put the API on my GitHub without breaking your license. I must make it impossible for other people to reproduce the mod's building without them explicitly downloading your mod manually to not break your license.

Just pointing that out. Besides, open-source modders earn money too. It's not like people donate to you just because you hand out dev builds and custom revolvers, is it? And if it is, that's not donating, that's *payment*. Learn the difference, it might save your life!
